wget https://pjreddie.com/media/files/alexnet.weights -O weight/alexnet.weights
wget https://pjreddie.com/media/files/darknet.weights -O weight/darknet.weights
wget https://pjreddie.com/media/files/vgg-16.weights -O weight/vgg-16.weights
wget https://pjreddie.com/media/files/extraction.weights -O weight/extraction.weights
wget https://pjreddie.com/media/files/darknet19.weights -O weight/darknet19.weights
wget https://pjreddie.com/media/files/darknet19_448.weights -O weight/darknet19_448.weights
wget https://pjreddie.com/media/files/densenet201.weights -O weight/densenet201.weights
wget https://pjreddie.com/media/files/darknet53.weights -O weight/darknet53.weights
wget https://pjreddie.com/media/files/darknet53_448.weights -O weight/darknet53_448.weights
wget https://pjreddie.com/media/files/tiny.weights -O weight/tiny.weights
